name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker push
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_ACCESSTOKEN: ${{ secrets.DOCKER_ACCESSTOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_ACCESSTOKEN
        docker build -t insyst3m/notification-telegram-bot:$(date +%s) -f Dockerfile .
        docker push insyst3m/notification-telegram-bot:$(date +%s)
        docker logout
