name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set docker tag
      run: |
        echo "tag=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT
      id: docker
      
    - uses: actions/checkout@v3
    - name: Docker push
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_ACCESSTOKEN: ${{ secrets.DOCKER_ACCESSTOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_ACCESSTOKEN
        cd Src
        docker build . -t insyst3m/notification-telegram-bot:${{ steps.docker.outputs.tag }}
        docker push insyst3m/notification-telegram-bot:${{ steps.docker.outputs.tag }}
        docker logout