name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag insyst3m/notification-telegram-bot:$(date +%s)
    - name: Docker push
      run: docker push insyst3m/notification-telegram-bot:$(date +%s)
