name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker push
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_ACCESSTOKEN: ${{ secrets.DOCKER_ACCESSTOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_ACCESSTOKEN
        cd Src
        docker build . -t insyst3m/notification-telegram-bot:latest
        docker push insyst3m/notification-telegram-bot:latest
        docker logout

  deploy:
    name: Webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}